#include"htmlwriter.h"
#include<fstream>
using namespace std;

HTMLWriter::HTMLWriter(const string& fileName, const string& content)
	:DocWriter(fileName, content) { //초기화리스트
	//DocWriter class의 생성자 호출 (부모꺼 사용)


	//자식클래스의 전용 멤버변수
	_fontName = "굴림";
	_fontSize = 3;
	_fontColor = "black";
}

HTMLWriter::HTMLWriter() {
	_fileName = "NoName.html";
	_fontName = "굴림";
	_fontSize = 3;
	_fontColor = "black";
}

HTMLWriter::~HTMLWriter() {}

void HTMLWriter::Write() { //메서드 오버라이딩
	//부모랑 쓰기방식이 달라서 오버라이드함

	ofstream of(_fileName.c_str());

	of << "<HTML><HEAD><TITLE>This document was generated by HTMLWriter</TITLE></HEAD>";
	of << "<H1>Content</H1>";

	of << "<Font name='" << _fontName << "' size='" << _fontSize << "' color='"<<_fontColor<<"'>";

	of << _content;
	of << "</FONT>";
	of << "</BODY></HTML>";
}

void HTMLWriter::SetFont(const string& fontName, int fontSize, const string& fontColor) {
	_fontName = fontName;
	_fontSize = fontSize;
	_fontColor = fontColor;
}